### ISSUE TITLE
slow init phase when using a 206Mb ASAGI file and v1.3.1

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#1337]
### Describe the bug

a setup with o5, single precision, 27 millions cells takes 23min to initialize the mesh, and 12 min to initialize the model, with 40 nodes of supermuc NG.

here is the log:
[4569986.with_asagi.txt](https://github.com/user-attachments/files/19954578/4569986.with_asagi.txt)

This seems unexpectedly large (I would expect 2-3min).

This is most probably related with asagi.

below the material file:
(ASAGI_files/casc16_ASAGI.nc has 206Mb)

```
i73yeq4@login03:/hppfs/scratch/0A/di73yeq4/2024-12-05_Mw7_California_Earthquak_nc75095651Solucion_strike_98_200m_o5_casc16_1km> cat yaml_files/material.yaml 
!Switch
[rho, mu, lambda]:  !IdentityMap
  components:
    - !AffineMap
          matrix:
            ua: [1.0, 0.0, 0.0]
            ub: [0.0, 1.0, 0.0]
            uc: [0.0, 0.0, 1.0]
          translation:
            ua: 0.0
            ub: 0.0
            uc: 0.0
          components: !Any
            - !ASAGI
                file: ASAGI_files/casc16_ASAGI.nc
                parameters: [rho, mu, lambda]
                var: data
                interpolation: linear
            - !ConstantMap
                map:
                 rho: 3330.
                 mu: 65942325000.
                 lambda: 81235350000.
```

### Expected behavior

Tell us what you want the code to do.

### To Reproduce

1. v1.3.1
2. intel (2023.1.0)
3. supermucNG
```
di73yeq4@login03:/hppfs/scratch/0A/di73yeq4/2024-12-05_Mw7_California_Earthquak_nc75095651Solucion_strike_98_200m_o5_casc16_1km> module list
Currently Loaded Modulefiles:
 1) admin/2.0   2) tempdir/1.0   3) lrz/1.0   4) user_spack/23.1.0   5) spack/23.1.0   6) intel/2023.1.0   7) intel-mpi/2021.9.0   8) intel-mkl/2023.1.0   9) python/3.10.10-extended  10) seissol/1.3.1-intel23-o5-elas-dunav-single-impi  

Key:
default-version  sticky  
```
4. Provide parameter/material files.

https://syncandshare.lrz.de/getlink/fiE6exBxKfWiUuWjH5Cuz5/slow_init.tar.gz

(note that a smaller mesh is set in parameters.par, but the larger mesh I used when initiating the issue is also in the tar file)
